# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 17:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MapEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='', primary_key=True, serialize=False, verbose_name='ID')),
                ('entityName', models.CharField(help_text='', max_length=60)),
                ('entityDescription', models.CharField(help_text='', max_length=300)),
                ('publishDate', models.DateTimeField(auto_now_add=True, help_text='')),
                ('startDate', models.DateTimeField(help_text='', null=True)),
                ('endDate', models.DateTimeField(help_text='', null=True)),
                ('lastModDate', models.DateTimeField(auto_now=True, help_text='', null=True)),
                ('geoLocationField', django.contrib.gis.db.models.fields.PointField(help_text='', srid=4326)),
                ('entityType', models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, to='MapApp.EventType')),
                ('owner', models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='', primary_key=True, serialize=False, verbose_name='ID')),
                ('lastLocation', django.contrib.gis.db.models.fields.PointField(help_text='', srid=4326)),
                ('user', models.OneToOneField(help_text='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
