# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapentity',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text=''),
        ),
        migrations.AlterField(
            model_name='mapentity',
            name='endDate',
            field=models.DateTimeField(blank=True, help_text='', null=True),
        ),
        migrations.AlterField(
            model_name='mapentity',
            name='entityDescription',
            field=models.TextField(help_text=b'Very awesome party at my place', max_length=300),
        ),
        migrations.AlterField(
            model_name='mapentity',
            name='entityName',
            field=models.CharField(help_text=b'Insert name here', max_length=60),
        ),
        migrations.AlterField(
            model_name='mapentity',
            name='entityType',
            field=models.ForeignKey(help_text=b'What type of event is it?', on_delete=django.db.models.deletion.CASCADE, to='MapApp.EventType'),
        ),
    ]
